package Utilities;

public enum Action
{
	CUSTOM(1),
    AlertAccept(2),
    AlertAuthenticate(3),
    AlertDissmis(4),
    AlertGetText(5),
    AlertSetText(6),
    Check(7),
    Clear(8),
    Click(9),
    ClickAndHold(10),
    ClickAndHoldOnObject(11),
    Close(12),
    DeselectAll(13),
    DeselectByIndex(14),
    DeselectByText(15),
    DeselectByValue(16),
    DoubleClick(17),
    DoubleClickOnObject(18),
    DragAndDrop(19),
    DragAndDropToObject(20),
    GoBack(21),
    GoForward(22),
    Highlight(23),
    KeyDown(24),
    KeyUp(25),
    MouseOver(26),
    Navigate(27),
    ObjectDisplayed(28),
    ObjectEnabled(29),
    ObjectSelected(30),
    Refresh(31),
    Release(32),
    ReleaseOnObject(33),
    RightClick(34),
    RightClickOnObject(35),
    Scroll(36),
    SelectByIndex(37),
    SelectByText(38),
    SelectByValue(39),
    SelectFrame(40),
    Submit(41),
    SwitchToFrame(42),
    Type(43),
    TypeAction(44),
    TypeJS(45),
    Uncheck(46),
    Wait(47),
    WaitForCondition(48),
    WaitForPageToLoad(49),
    WaitForPopUp(50),
    WindowFocus(51),
    VerifyProperty(52),
    VerifyIfExists(53),
    RobotKeyboard(54),
    Component(55),
    CheckOption(56),
    GetProperty(57),
    SwitchToWindow(58),
    Quit(59),
    TypeSecure(60), 
    SwitchToDefaultContent(61), 
    VerifyText(62),
    AlertAcceptIfExist(63), 
    MouseOverAndClick(64), 
    TypeRandomValue(65),
    SecureRobotKeyboard(66),
	NoAction(67),
	WIN_SwitchToActiveElement(68),
	WIN_Click(69),
	WIN_Type(70),
	WIN_Wait(71), 
	SelectListByText(72), 
	SelectSpinnerByText(73),
    ResizeWindow(74),
    MultiTouch(75),
    UserSays(76),
    BotSays(77),
    Stop(78),
    Get(79),
    Post(80),
    Put(81),
    Delete(82),
    ExecuteSOAPUITest(83),
	TypeIfValueExists(84),
    SelectByIndexIfValueExists(85),
    SelectByTextIfValueExists(86),
    SelectByValueIfValueExists(87),
    SelectListByTextIfValueExists(88), 
    VerifyTitle(89),
    Drag(90),
    Drop(91);
	
	private final int value;

	Action(final int newValue) {
        value = newValue;
    }

    public int getValue() { return value; }
}

